name: CastAway
main: de.minestar.castaway.core.CastAwayCore
version: ${pom.version}
depend: [MineStarLibrary]
commands:
    castaway:
        description: SuperCommandHolder for all subcommands
        usage: /castaway <SubCommand>